name: Build and Push to ECR

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter version (e.g. 1.0.0)'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get image tag
        id: tag
        run: |
          if [[  $GITHUB_REF == refs/tags/*  ]]; then            
            echo "TAG_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for branch        
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platform: linux/arm64/v8
          cache-from: type=registry,ref=surya22119/custom-nextjs-prod:buildcache
          cache-to: type=registry,ref=surya22119/custom-nextjs-prod:buildcache,mode=max
          tags: |
            surya22119/custom-nextjs-prod:${{ steps.tag.outputs.TAG_NAME }}
            surya22119/custom-nextjs-prod:latest


