name: Build and Push to ECR

on:
  # push:
  #   branches:
  #     - main

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Get tag image and check for sematic versioning
        id: tag
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then            
            if [[ "$GITHUB_REF_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            else
              echo "Error: Use proper semantic versioning for tags (e.g., v1.0.0)"
              echo "Provided values:"
              echo "  GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
              echo "  GITHUB_REF: $GITHUB_REF"
              echo "  GITHUB_REF_NAME: $GITHUB_REF_NAME"
              exit 1
            fi
          else
            echo "This is not a tag. Proceeding with staging."
            echo "TAG_NAME=staging" >> $GITHUB_OUTPUT
          fi

      - name: Checkout code
        uses: actions/checkout@v4            

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for branch        
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platform: linux/arm64/v8
          cache-from: type=registry,ref=surya22119/custom-nextjs-prod:buildcache
          cache-to: type=registry,ref=surya22119/custom-nextjs-prod:buildcache,mode=max
          tags: |
            surya22119/custom-nextjs-prod:${{ steps.tag.outputs.TAG_NAME }}
            surya22119/custom-nextjs-prod:latest


