name: Docker Build and Push 

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          # For tags
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
            echo "BRANCH_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            echo "IS_TAG=true" >> $GITHUB_OUTPUT
          else
            # For branches
            echo "BRANCH_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            echo "IS_TAG=false" >> $GITHUB_OUTPUT
          fi    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for branch
        if: steps.version.outputs.IS_TAG == 'false'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=registry,ref=surya22119/custom-nextjs-prod:buildcache
          cache-to: type=registry,ref=surya22119/custom-nextjs-prod:buildcache,mode=max
          tags: |
            surya22119/custom-nextjs-prod:${{ steps.version.outputs.BRANCH_VERSION }}
            surya22119/custom-nextjs-prod:latest

      - name: Build and push Docker image for tag
        if: steps.version.outputs.IS_TAG == 'true' 
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=registry,ref=surya22119/custom-nextjs-prod:buildcache
          cache-to: type=registry,ref=surya22119/custom-nextjs-prod:buildcache,mode=max
          tags: |
            surya22119/custom-nextjs-prod:${{ steps.version.outputs.TAG_VERSION }}
            surya22119/custom-nextjs-prod:${{ steps.version.outputs.BRANCH_VERSION }}
            surya22119/custom-nextjs-prod:latest
